apiVersion: v1
kind: Pod
metadata:
  name: kubia-named
  labels:
    app: kubia-named
spec:
  containers:
  - name: broker
    image: nginx
    ports:
    - name: http
      port: 80
      targetPort: 80
  - name: webapp
    image: luksa/kubia
    ports:
    - name: https
      port: 8080
      targetPort: https
