apiVersion: apps/v1
kind: Deployment
metadata:
  name: required-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: required
  template:
    metadata:
      labels:
        app: required
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: availability-zone
                  operator: In
                  values: 
                  - zone1
      containers:
      - args:
        - sleep
        - "99999"
        image: busybox
        name: main
