apiVersion: apps/v1
kind: Deployment
metadata:
  name: required-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: required
  template:
    metadata:
      labels:
        app: required
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: zone-name
                  operator: In
                  values: 
                  - zone2
                - key: share-type
                  operator: In
                  values:
                  - shared
      containers:
      - args:
        - sleep
        - "99999"
        image: busybox
        name: main
